name: CI

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.23.5

      - name: Install
        run: pnpm install

      - name: Build
        run: pnpm run build

  typecheck:
    name: Typechecker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.23.5

      - name: Install
        run: pnpm install

      - name: Typecheck
        run: pnpm run typecheck

  test:
    name: Unit and Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.23.5

      - name: Install
        run: pnpm install

      - name: Test
        run: pnpm run test -- --ci --coverage --maxWorkers=2

  lint:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.23.5

      - name: Install
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Lint
        run: pnpm run lint
